version: "3"
services:
  nextjs:
    build: ./ps-housetech-frontend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://ps-housetech.uni-muenster.de/api/health-check-next || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  api:
    build: ./ps-housetech-backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://ps-housetech.uni-muenster.de/api/health-check-flask || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://ps-housetech.uni-muenster.de/api/health-check-nginx || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3